services:
  db:
    image: postgres:10.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: simple_microblog
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"    
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/microblog
    ports:
      - "3000:3000"
    depends_on:
      - db