default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: simple_microblog
  username: postgres
  password: 12345
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: simple_microblog
  username: postgres
  password: 12345
  host: localhost
