default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345

development:
  <<: *default
  encoding: unicode
  pool: 5
  database: simple_microblog
  username: postgres
  password: 12345

#production:
#  <<: *default
#  adapter: postgresql
#  database: <%= ENV['DATABASE_NAME'] %>
#  host: <%= ENV['DATABASE_ENDPOINT'] %>
#  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
#  username: <%= Rails.application.credentials.dig(:production, :database_username) %>
#  password: <%= Rails.application.credentials.dig(:production, :database_password) %>

test:
  <<: *default
  encoding: unicode
  pool: 5
  database: test_simple_microblog
  username: postgres
  password: 12345
